ToDoApp/ToDoApp/Models/Entities/Assignee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApp.Models.Entities
{
    public class Assignee
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }

        public List<Todo> Todos { get; set; }

        public Assignee(string name)
        {
            Name = name;
        }
    }
}

ToDoApp/ToDoApp/Models/Entities/Todo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApp.Models.Entities
{
    public class Todo
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public bool IsUrgent { get; set; }
        public bool IsDone { get; set; }
        public long? AssignedId { get; set; }
        public Assignee Assignee { get; set; }
        public Todo(string title)
        {
            Title = title;
            IsUrgent = false;
            IsDone = false;
        }
    }
}

ToDoApp/ToDoApp/Models/Entities/ViewAssignee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApp.Models.Entities
{
    public class ViewAssignee
    {
        public Assignee Asgn { get; set; }
        public List<Assignee> Assignees { get; set; }
        public Todo Todo { get; set; }
    }
}

ToDoApp/ToDoApp/Models/Entities/ViewTodo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApp.Models.Entities
{
    public class ViewTodo
    {
        public Todo Td { get; set; }
        public List<Todo> Todos { get; set; }

        public ViewTodo()
        {
            Todos = new List<Todo>();
        }
    }
}

ToDoApp/ToDoApp/Controllers/AssigneeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ToDoApp.Models.Entities;
using ToDoApp.Services;

namespace ToDoApp.Controllers
{
    [Route("assignee")]
    public class AssigneeController : Controller
    {
        AssigneeService AS { get; set; }
        public AssigneeController(AssigneeService assigneeService)
        {
            AS = assigneeService;
        }
        public IActionResult Index()
        {
            ViewAssignee model = new ViewAssignee();
            model.Assignees = AS.FindAll();
            return View(model);
        }

        [HttpPost("edit")]
        public IActionResult Edit(long id)
        {
            return View(id);
        }

        [HttpPost("change")]
        public IActionResult Change(long id, string name, string email)
        {
            AS.Change(id, name, email);
            return RedirectToAction("Index");
        }

        [HttpPost("delete")]
        public IActionResult Delete(long id)
        {
            AS.Delete(AS.FindById(id));
            return RedirectToAction("Index");
        }

        [HttpGet("new")]
        public IActionResult NewAssignee()
        {
            return View();
        }

        [HttpPost("add")]
        public IActionResult Add(string name, string email)
        {
            AS.Add(name, email);
            return RedirectToAction("Index");
        }
    }
}

ToDoApp/ToDoApp/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using ToDoApp.Models.Entities;
using ToDoApp.Services;

namespace ToDoApp.Controllers
{
    [Route("todo")]
    public class TodoController : Controller
    {
        public TodoService TS { get; set; }
        public AssigneeService AS { get; set; }
        public Todo TD { get; set; }
        public TodoController(TodoService todoService, AssigneeService assigneeService)
        {
            TS = todoService;
            AS = assigneeService;
        }

        [HttpGet("list")]
        [HttpGet("")]
        public IActionResult List()
        {
            ViewTodo model = new ViewTodo();
            model.Todos = TS.FindAll();
            return View(model);
        }

        [HttpGet("new")]
        public IActionResult NewTask()
        {
            return View();
        }

        [HttpPost("add")]
        public IActionResult Add(string task, bool isUrgent)
        {
            TS.Add(task, isUrgent);
            return RedirectToAction("List");
        }

        [HttpPost("delete")]
        public IActionResult Delete(long id)
        {
            TS.Delete(TS.FindById(id));
            return RedirectToAction("List");
        }

        [HttpPost("edit")]
        public IActionResult Edit(long id)
        {
            ViewAssignee model = new ViewAssignee();
            model.Todo = TS.FindById(id);
            model.Assignees = AS.FindAll();
            return View(model);
        }

        [HttpPost("change")]
        public IActionResult Change(long id, string task, bool urgent, bool done, long assignee)
        {
            TS.Change(id, task, urgent, done, assignee);
            AS.AddTodo(assignee, TS.FindById(id));
            return RedirectToAction("List");
        }

        [HttpPost("find")]
        public IActionResult Find(string word)
        {
            ViewTodo model = new ViewTodo();
            model.Todos = TS.FindAll().Where(x => x.Title.Contains(word)).ToList();
            return View("List", model);
        }
    }
}

ToDoApp/ToDoApp/Views/Assignee/Edit.cshtml
@model long
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <h1>Edit todo</h1>
    <form action="change" method="post">
        <label for="name">New name</label>
        <input type="text" name="name" />
        <label for="email">New email</label>
        <input type="text" name="email" />
        <input type="hidden" name="id" value=@Model>
        <button type="submit">Change</button>
    </form>
    <a href="list">Cancel</a>
</body>
</html>

ToDoApp/ToDoApp/Views/Assignee/Index.cshtml
@model ToDoApp.Models.Entities.ViewAssignee
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <h1>Assignees</h1>
    <a href="assignee/new">Add assignee</a>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Assignees)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Email</td>
                    <td>
                        <form action="assignee/edit" method="post">
                            <button value=@item.Id name="id">Edit</button>
                        </form>
                    </td>
                    <td>
                        <form action="/assignee/delete" method="post">
                            <button value=@item.Id name="id">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>
<style>
    table, td, th {
        border: 1px solid black;
    }

    table {
        border-collapse: collapse;
        width: 25%;
    }
</style>

ToDoApp/ToDoApp/Views/Assignee/NewAssignee.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <form action="add" method="post">
        <label for="name">Enter Name</label>
        <input type="text" name="name" />
        <label for="email">Enter Email</label>
        <input type="text" name="email" />
        <button type="submit">Add</button>
    </form>
</body>
</html>

ToDoApp/ToDoApp/Views/Todo/Edit.cshtml
@model ToDoApp.Models.Entities.ViewAssignee  
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <h1>Edit todo</h1>
    <form action="change" method="post">
        <label for="task">Rename task</label>
        <input type="text" name="task" />
        <label for="urgent">Urgent</label>
        @if (Model.Todo.IsUrgent == true)
        {
            <input value=true type="checkbox" name="urgent" checked>
        }
        else
        {
            <input value=false type="checkbox" name="urgent">
        }
        <label for="done">Done</label>
        @if (Model.Todo.IsDone == true)
        {
            <input value=true type="checkbox" name="done" checked>
        }
        else
        {
            <input value=false type="checkbox" name="done">
        }
        <input type="hidden" name="id" value=@Model.Todo.Id>
        <label for="assignee">Assigne</label>
        <select name="assignee" id="assignee">
            <option></option>
            @foreach (var item in Model.Assignees)
            {
                <option value=@item.Id>@item.Name</option>
            }
        </select>
        <button type="submit">Change</button>
    </form>
    <a href="list">Cancel</a>
</body>
</html>

ToDoApp/ToDoApp/Views/Todo/Index.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
</body>
</html>

ToDoApp/ToDoApp/Views/Todo/List.cshtml
@model ToDoApp.Models.Entities.ViewTodo
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <h1>Todos for today:</h1>
    <form action="todo/find" method="post">
        <label for="word">Find keyword</label>
        <input type="text" name="word" />
        <button type="submit">Find</button>
    </form>
    <a href="todo/list">Show all</a>
    <a asp-controller="Assignee" asp-action="Index">List of Assignees</a>
    <a href="todo/new">New task</a>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Task</th>
                <th>IsUrgent</th>
                <th>IsDone</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Todos)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Title</td>
                    <td>@item.IsUrgent</td>
                    <td>@item.IsDone</td>
                    <td>
                        <form action="/todo/delete" method="post">
                            <button value=@item.Id name="id">Delete</button>
                        </form>
                    </td>
                    <td>
                        <form action="/todo/edit" method="post">
                            <button value=@item.Id name="id">Edit</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>
<style>
    table, td, th {
        border: 1px solid black;
    }

    table {
        border-collapse: collapse;
        width: 25%;
    }
</style>

ToDoApp/ToDoApp/Views/Todo/NewTask.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <form action="add" method="post">
        <label for="task">Enter Task</label>
        <input type="text" name="task" />
        <label for="isUrgent">Is Urgent</label>
        <select name="isUrgent">
            <option value=false>No</option>
            <option value=true>Yes</option>
        </select>
        <button type="submit">GO</button>
    </form>
</body>
</html>